FROM nginx

# nginx conf
copy ./nginx.conf /etc/nginx/nginx.conf


copy ./img/*.png /usr/share/nginx/html/img/
copy ./*.html /usr/share/nginx/html
copy ./*.css /usr/share/nginx/html
copy ./*.js /usr/share/nginx/html
